/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import FeatureCard from "../components/FeatureCard";
import Showcase from "../components/Showcase";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    window.onscroll = function () {
      if (
        document.body.scrollTop > 200 ||
        document.documentElement.scrollTop > 200
      ) {
        document.querySelector("#navbar").classList.remove("text-white")
        document.querySelector("#navbar").classList.add("bg-white", "text-black")
      } else  {
        document.querySelector("#navbar").classList.remove("bg-white", "text-black")
        document.querySelector("#navbar").classList.add("text-white")
      }
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/fontawesome/css/regular.min.css" />
        <link rel="stylesheet" href="/fontawesome/css/brands.min.css" />
        <link rel="stylesheet" href="/fontawesome/css/fontawesome.min.css" />
      </Head>

      <main className="flex flex-col">
        <section className="h-screen backdrop-filter backdrop-blur-lg hero-bg">
          <section className="w-full flex items-center px-2 md:px-24 filter h-full bg-black bg-opacity-90">
            
              <nav id="navbar" className="flex shadow items-center justify-between w-full z-10 px-2 md:px-24 fixed top-0 right-0 left-0  py-6 text-white">
                <span>Logo</span>
                <ul className="flex space-x-4">
                  <li className="font-bold ">
                    <a>Create Account/Login</a>
                  </li>
                  <li className="font-bold">
                    <a>Properties</a>
                  </li>
                </ul>
              </nav>

            <div className="text-white">
              <p className="font-bold text-4xl">Discover your new home</p>
              <p className="mt-2">
                Helping 100 million renter find their perfect fit
              </p>
              <section className="flex mt-8 border rounded border-white">
                <input
                  placeholder="Search"
                  className="w-full px-4 search-input bg-transparent outline-none"
                />
                <button className="p-3 bg-gradient-to-tr from-green-500 to-blue-900">
                  Search
                </button>
              </section>
            </div>
          </section>
        </section>

        <section className="flex bg-[#ebebeb] flex-col py-16 items-center">
          <h1 className="font-bold text-3xl text-green-800">
            Rent an appartment in your location
          </h1>
          <p className="text-lg mt-2 text-green-800">
            We are here to help you solve your accomodation challenges
          </p>
          <section
            style={{
              scrollbarWidth: "none",
            }}
            className="w-full px-6 overflow-auto mt-6 flex space-x-6"
          >
            <Showcase img_url="/images/nice_house.jpg"/>
            <Showcase img_url="/images/nice_house1.jpg"/>
            <Showcase img_url="/images/nice_house2.jpg"/>
            <Showcase img_url="/images/nice_house.jpg"/>
            <Showcase img_url="/images/nice_house2.jpg"/>
            <Showcase img_url="/images/nice_house1.jpg"/>
          </section>
          <button className="mt-8 from-green-800 to-green-600 text-white p-4 rounded-md bg-gradient-to-tr">
            See More
          </button>
        </section>

        <section className="flex flex-col px-4 md:px-48 items-center py-16">
          <h1 className="font-bold text-3xl text-green-800">
            Get an Apartment Anywhere
          </h1>
          <p className="text-lg mt-2 text-green-800">Let us serve you</p>
          <section className="flex flex-wrap w-full mt-16">
            <section className="w-full md:w-1/2 relative">
              <figure className="relative md:w-[350px] md:h-[337px] mt-28 ml-16 overflow-hidden rounded-3xl">
                <div className="p-4 bg-gradient-to-b absolute top-0 left-0 right-0 bottom-0 flex items-end from-transparent via-transparent to-gray-700">
                  <p className="font-light text-white">
                    1327 E Moreland St, Phoenix, AZ 85006, Garfield
                  </p>
                </div>
                <img
                  className="w-full h-full object-cover"
                  src="/images/woman.png"
                />
              </figure>
              <figure className="md:w-[350px] md:h-[337px] absolute top-0 left-0 overflow-hidden rounded-3xl shadow-2xl">
                <div className="p-4 bg-gradient-to-b absolute top-0 left-0 right-0 bottom-0 flex items-end from-transparent via-transparent to-gray-700">
                  <p className="font-light text-white">
                    1327 E Moreland St, Phoenix, AZ 85006, Garfield
                  </p>
                </div>
                <img
                  className="w-full h-full object-cover"
                  src="/images/freshama.png"
                />
              </figure>
            </section>
            <section className="w-full mt-4 md:w-1/2 flex flex-col">
              <h1 className="font-bold text-3xl text-green-800">
                The #1 site for Renters
              </h1>
              <p className="text-green-800 text-[22px] mt-4">
                Choose from over 1 million apartments, houses, condos, and
                townhomes for rent. Search over 1.1 million listings including
                apartments, houses, condos, and townhomes available for rent.
                You’ll find your next home, in any style you prefer.
              </p>
            </section>
          </section>
        </section>

        <section className="relative h-[600px]">
          <img
            alt="csdcd"
            className="w-full object-fill h-full"
            src="/images/rectangle.png"
          />
          <section className="absolute top-0 right-0 bottom-0 left-0 p-4 flex items-center justify-around">
            <div className="text-white w-full md:w-1/3">
              <p className="font-bold text-2xl">Renting Made Simple</p>
              <p className="mt-4">
                Browse the highest quality listings, apply online, sign your
                lease, and even pay your rent from any device. Find a House,
                request inspection, make a choice and then make payment without
                hurdles{" "}
              </p>
            </div>
            <div className="w-1/3">
              <div></div>
            </div>
          </section>
        </section>

        <section className="flex flex-col p-2 flex-wrap py-12 items-center">
          <h1 className="font-bold text-3xl text-green-700">
            How we serve You Better
          </h1>
          <p className="text-lg mt-3 text-green-700">Let us serve you well</p>
          <section className="w-full md:px-28 flex mt-4 flex-wrap pb-32">
            <FeatureCard
              img_url="/images/icons/Heart1.png"
              title="User Friendly"
              desc="We have great user interface that makes navigating accounting tasks fun and easy"
            />
            <FeatureCard
              img_url="/images/icons/Shield.png"
              title="Safe & Secure"
              desc="We have great user interface that makes navigating accounting tasks fun and easy."
            />
            <FeatureCard
              img_url="/images/icons/AlarmIcon.png"
              title="Real-time Notifications"
              desc="We have great user interface that makes navigating accounting tasks fun and easy."
            />
            <FeatureCard
              img_url="/images/icons/Heart.png"
              title="Capture Receipts"
              desc="We have great user interface that makes navigating accounting tasks fun and easy."
            />

            <FeatureCard
              img_url="/images/icons/ChatIcon.png"
              title="24/7 Chat"
              desc="We have great user interface that makes navigating accounting tasks fun and easy."
            />
            <FeatureCard
              img_url="/images/icons/Heart1.png"
              title="Cloud-hosted"
              desc="We have great user interface that makes navigating accounting tasks fun and easy."
            />
          </section>
        </section>
        <footer className="bg-[#222222] flex-wrap justify-between flex flex-col md:flex-row text-white px-16 py-16">
          <section className="w-full md:w-1/3">
            <p>
              Connect with us on various social media platforms. We are here for
              you
            </p>
            <p>Connect with us on social media </p>
            <section className="flex mt-8 space-x-4 text-white">
              <a className="text-2xl">
                <i className="fab fa-facebook-f"></i>
              </a>
              <a className="text-2xl">
                <i className="fab fa-instagram"></i>
              </a>
              <a className="text-2xl ">
                <i className="fab fa-youtube"></i>
              </a>
              <a className="text-2xl ">
                <i className="fab fa-twitter"></i>
              </a>
              <a className="text-2xl">
                <i className="far fa-envelope"></i>
              </a>
            </section>
          </section>
          <section>
            <h1 className="text-xl">Content</h1>
            <div className="flex mt-2 flex-col">
              <a>Get Started</a>
              <a>Pricing</a>
              <a>Technology</a>
              <a>Login</a>
              <a>Resource</a>
            </div>
          </section>
          <section>
            <h1 className="text-xl">Links</h1>
            <div className="flex mt-4 flex-col">
              <a>Team</a>
              <a>Jobs</a>
              <a>Press</a>
              <a>About US</a>
            </div>
          </section>
          <section className="flex space-y-3 flex-col">
            <p className="font-semibold text-xl">Stay Connected</p>
            <p>Subscribe to our news letter</p>
            <section className="rounded flex p-2 bg-white shadow-inner">
              <input
                className="text-gray-500 outline-none"
                placeholder="Enter Email"
              />
              <button className="text-white rounded bg-green-700">
                <img className="w-8" src="/images/icons/send.png" />
              </button>
            </section>

            <div className="flex text-white">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
              <p>Apartments@apartrments.com</p>
            </div>
            <div className="flex text-white">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                />
              </svg>
              <p>+419000877364, +23408987645</p>
            </div>
          </section>
        </footer>
      </main>
    </>
  );
}
